HOSTS:
  ubuntu-14-04:
    roles:
      - master
    platform: ubuntu-14.04-amd64
    image: electrical/ubuntu:14.04
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -yq ruby ruby1.9.1-dev libaugeas-dev libaugeas-ruby lsb-release wget net-tools curl'
    docker_preserve_image: true
    hypervisor: docker

CONFIG:
  # log_level: debug
  type: foss
